import "./main.scss"
import "./components/footer-section/footer-section.js";
import "./components/form-change-item/form-change-item.js";
import "./components/form-create-item/form-create-item.js";
import "./components/form-registration/form-registration.js";
import "./components/header-section/header.js";
import "./components/hero-section/hero-section.js";
import "./components/item-card/item-card.js";
import "./pages/main-page/main-section.js";
import "./pages/favourites-page/favourites-page.js";
